### ISSUE TITLE
Implement version control for endpoints

### ISSUE THREAD

**Issue by benediktvaldez** [kristjanmik/apis#119]
Latest version will be returned by default, unless otherwise specified in URL

```
apis.is/weather/:forecasts      < returns latest version of endpoint
apis.is/weather/v1/:forecasts   < returns v1 of endpoint
```

Middleware has to be able to alter the version on the endpoint

**Comment by rthor** [comment]
Is this done or are you just not going to implement it?

**Comment by kristjanmik** [comment]
We are cleaning up the project and everything was therefore archived. Everything will be considered in the new update, see: https://github.com/kristjanmik/apis/tree/v2
