### ISSUE TITLE
Add endpoint to iceland.adagios.org or the same data sources they use

### ISSUE THREAD

**Issue by elvarb** [kristjanmik/apis#124]
Adagios is a open source project supported by Opin Kerfi
http://iceland.adagios.org/iceland/

They have access to lots of information there, especially healthcare information.

There is an API at http://iceland.adagios.org/iceland/

It would be nice if apis had access to this information, prefered would be the same raw data they have access to.

**Comment by kristjanmik** [comment]
@koddsson did you find anything more usefull in the dataset or should I close down this issue?

**Comment by koddsson** [comment]
I'll check it out later tonight @kristjanmik!

**Comment by koddsson** [comment]
@kristjanmik Yeah I think this issue can be closed!
