### ISSUE TITLE
How do I start the dev server?

### ISSUE THREAD

**Issue by koddsson** [kristjanmik/apis#147]
I installed the dependencies and ran `npm run start` but didn't manage to get a connection!

![screen shot 2015-02-01 at 22 45 57](https://cloud.githubusercontent.com/assets/318208/5994255/e8ee0a8e-aa63-11e4-8483-4f6d9e427f8e.png)

cc/ @benediktvaldez @MiniGod @kristjanmik

**Comment by kristjanmik** [comment]
try
curl 127.0.0.1:3100
;)

**Comment by koddsson** [comment]
Oh lawd. Sorry!

**Comment by MiniGod** [comment]
Why did `localhost` fail?

**Comment by koddsson** [comment]
Not sure :u7121:

**Comment by kristjanmik** [comment]
Missing mappings in /etc/hosts OSX ?
